import { z } from 'zod';
import {
  ConflictError,
  NotFoundError,
  ValidationError,
  authz,
  logger,
  newId,
  platformDb,
  recordAudit,
  transaction,
  type TenantContext,
} from '@itsm/platform';
import { placeholdersIn } from '@itsm/module-workflow';
import { CAPABILITY_CATALOGUE, isCapability, type Capability } from '../domain/capabilities.js';
import { SHIPPED_PROMPTS } from '../seed/prompts.js';

/**
 * The prompt registry.
 *
 * Prompts are the deployment's, like plans and packs: no `tenant_id`, one set
 * of rows every tenant reads, written only by a platform operator. A tenant
 * that could rewrite its own prompt could rewrite its way past every
 * evaluation threshold the release gate depends on (doc 13 §5), which is the
 * whole reason the gate exists.
 *
 * A version is immutable once written. Changing a prompt means writing the
 * next version, evaluating it, and promoting it — three separate acts, so that
 * "what was this answer generated by" has an answer a year later.
 */

/** The paths a prompt may read. Anything else is refused before it is saved. */
export const PROMPT_PATHS = [
  'ticket',
  'requester',
  'conversation',
  'evidenceList',
  'tone',
  'language',
] as const;

export const promptVersionSchema = z.object({
  systemPrompt: z.string().min(20).max(4000),
  template: z.string().min(20).max(20_000),
  changeNote: z.string().max(500).optional(),
});
export type PromptVersionInput = z.input<typeof promptVersionSchema>;

/**
 * Refuses a template that reads something the assembler does not provide.
 *
 * The renderer is strict, so an unknown path would fail every call at run
 * time — after the prompt was promoted, in production, on somebody's ticket.
 * Catching it at the moment it is written costs nothing and is the same check
 * the workflow engine makes before it publishes a graph.
 */
export function unknownPaths(template: string): string[] {
  const known = new Set<string>(PROMPT_PATHS);
  return placeholdersIn(template).filter((path) => {
    const root = path.split('.')[0]!;
    return !known.has(root);
  });
}

export async function listPrompts() {
  return platformDb().aiPrompt.findMany({ orderBy: { key: 'asc' }, include: { versions: { orderBy: { version: 'desc' } } } });
}

export async function getPrompt(key: string) {
  const prompt = await platformDb().aiPrompt.findFirst({
    where: { key },
    include: { versions: { orderBy: { version: 'desc' } } },
  });
  if (!prompt) throw new NotFoundError('prompt', key);
  return prompt;
}

/**
 * The version a call renders, or null when nothing has been promoted.
 *
 * Seeds once and looks again if the prompt is not there at all. The boot seed
 * is deliberately not awaited — nothing else in `bootstrapModules` is, and a
 * database round trip in a synchronous boot path is its own problem — so the
 * first request after a cold start can arrive before it has landed. Refusing
 * that request would be a confusing five seconds after every deploy, and
 * seeding is idempotent.
 */
export async function currentVersionOf(key: string) {
  let prompt = await platformDb().aiPrompt.findFirst({ where: { key } });
  if (!prompt && SHIPPED_PROMPTS.some((shipped) => shipped.key === key)) {
    await seedAiPrompts();
    prompt = await platformDb().aiPrompt.findFirst({ where: { key } });
  }
  if (!prompt?.currentVersion) return null;
  return platformDb().aiPromptVersion.findFirst({ where: { promptKey: key, version: prompt.currentVersion } });
}

/** The next draft version of a prompt. Never edits one that already exists. */
export async function savePromptVersion(ctx: TenantContext, key: string, input: PromptVersionInput) {
  authz.require(ctx, 'platform.ai.prompt');
  const parsed = promptVersionSchema.parse(input);

  // Both halves: the gateway renders the system prompt strictly as well, so
  // an unknown path there fails every call in exactly the same way.
  const unknown = [...new Set([...unknownPaths(parsed.systemPrompt), ...unknownPaths(parsed.template)])];
  if (unknown.length > 0) {
    throw new ValidationError(
      `this prompt reads ${unknown.join(', ')}, which the context assembler does not provide`,
      unknown.map((path) => ({ field: path, code: 'unknown_path', message: `known paths are ${PROMPT_PATHS.join(', ')}` })),
    );
  }

  const db = platformDb();
  const prompt = await db.aiPrompt.findFirst({ where: { key } });
  if (!prompt) throw new NotFoundError('prompt', key);

  const latest = await db.aiPromptVersion.findFirst({ where: { promptKey: key }, orderBy: { version: 'desc' } });
  const version = (latest?.version ?? 0) + 1;

  const created = await db.aiPromptVersion.create({
    data: {
      id: newId(),
      promptKey: key,
      version,
      systemPrompt: parsed.systemPrompt,
      template: parsed.template,
      status: 'draft',
      changeNote: parsed.changeNote ?? null,
    },
  });

  await transaction(ctx, (tx) =>
    recordAudit(tx, ctx, {
      action: 'ai.prompt.version.saved',
      targetType: 'ai_prompt',
      targetId: key,
      after: { version, changeNote: parsed.changeNote ?? null },
    }),
  );
  return created;
}

/**
 * Promotes a version, if its evaluation says it may be.
 *
 * This is the release gate in one function. A version with no evaluation run,
 * or whose best run is below its dataset's threshold, is refused — and the
 * refusal names the score and the threshold, because "not allowed" without a
 * number is an argument rather than a control.
 */
export async function promotePrompt(ctx: TenantContext, key: string, version: number) {
  authz.require(ctx, 'platform.ai.prompt');
  const db = platformDb();

  const prompt = await db.aiPrompt.findFirst({ where: { key } });
  if (!prompt) throw new NotFoundError('prompt', key);
  if (prompt.currentVersion === version) throw new ConflictError(`version ${version} of ${key} is already the one in use`);

  const candidate = await db.aiPromptVersion.findFirst({ where: { promptKey: key, version } });
  if (!candidate) throw new NotFoundError('prompt version', `${key}@${version}`);

  const dataset = datasetFor(prompt.capability);
  if (dataset) {
    const best = await db.aiEvalRun.findFirst({
      where: { promptVersionId: candidate.id },
      orderBy: { score: 'desc' },
    });
    if (!best) {
      throw new ValidationError(
        `version ${version} of ${key} has not been evaluated, so it cannot be promoted; run it against the ${dataset} dataset first`,
      );
    }
    if (!best.passed) {
      throw new ValidationError(
        `version ${version} of ${key} scored ${best.score.toFixed(2)} against a threshold of ${best.threshold.toFixed(2)}, so it stays where it is`,
      );
    }
  }

  const previous = prompt.currentVersion;
  await db.aiPromptVersion.updateMany({ where: { promptKey: key, status: 'published' }, data: { status: 'retired' } });
  await db.aiPromptVersion.update({
    where: { id: candidate.id },
    data: { status: 'published', publishedAt: new Date() },
  });
  await db.aiPrompt.update({ where: { key }, data: { currentVersion: version } });

  await transaction(ctx, async (tx) => {
    await recordAudit(tx, ctx, {
      action: 'ai.prompt.promoted',
      targetType: 'ai_prompt',
      targetId: key,
      before: { version: previous },
      after: { version },
    });
  });

  logger.info('AI prompt promoted', { key, from: previous, to: version });
  return { key, version, previous };
}

function datasetFor(capability: string): string | null {
  return isCapability(capability) ? CAPABILITY_CATALOGUE[capability as Capability].datasetKey : null;
}

/**
 * Writes the shipped prompts at boot.
 *
 * Idempotent, and it never edits a version that already exists: an operator
 * who has written version 3 keeps it, and a deployment that ships a new
 * version 1 does not overwrite the history. The shipped version is published
 * **by release** rather than by an evaluation run — there is nothing to
 * evaluate against at boot, and possibly no provider at all — and the unit
 * suite is what gives that teeth: it runs every shipped prompt against its own
 * dataset, so a prompt that would fail its threshold cannot be released in the
 * first place. Everything written after release is promoted by evaluation.
 */
export async function seedAiPrompts(): Promise<{ created: number }> {
  const db = platformDb();
  let created = 0;

  for (const shipped of SHIPPED_PROMPTS) {
    const existing = await db.aiPrompt.findFirst({ where: { key: shipped.key } });
    if (existing) continue;

    await db.aiPrompt.create({
      data: {
        key: shipped.key,
        capability: shipped.capability,
        name: shipped.name,
        description: shipped.description,
        currentVersion: 1,
      },
    });
    await db.aiPromptVersion.create({
      data: {
        id: newId(),
        promptKey: shipped.key,
        version: 1,
        systemPrompt: shipped.systemPrompt,
        template: shipped.template,
        status: 'published',
        publishedAt: new Date(),
        changeNote: 'shipped with the deployment',
      },
    });
    created += 1;
  }

  if (created > 0) logger.info('AI prompts seeded', { created });
  return { created };
}
