/** `@itsm/sdk` — the typed client every application talks to the API through. */
export { ApiError, createClient, type Client, type ClientOptions, type RequestOptions } from './client.js';
export { ticketQuery, workbench, type TicketFilter, type Workbench } from './resources/workbench.js';
export {
  admin,
  type Admin,
  type FieldRow,
  type FlagRow,
  type OrganisationRow,
  type PermissionRow,
  type PlanRow,
  type SettingRow,
  type TeamRow,
  type TenantRow,
  type UserRow,
} from './resources/admin.js';
export {
  builders,
  type Builders,
  type CalendarRow,
  type Catalogue,
  type FormRow,
  type RequestTypeRow,
  type RuleFacts,
  type RuleRow,
  type RuleTestResult,
  type Rules,
  type ServiceRow,
  type Sla,
  type SlaPolicyRow,
  type SlaTargetRow,
  type WorkflowRow,
  type WorkflowRunRow,
  type WorkflowValidation,
  type Workflows,
} from './resources/builders.js';
export {
  portal,
  queueable,
  type QueueableRequest,
  type Article,
  type ApprovalRequest,
  type CatalogueItem,
  type CatalogueItemDetail,
  type Portal,
  type SearchHit,
  type SubmitResult,
} from './resources/portal.js';
export type {
  AiCapability,
  AiJob,
  ConfidenceBand,
  JobSuggestion,
  Me,
  Page,
  SlaTimer,
  SlaTimers,
  Suggestion,
  SuggestionEvidence,
  SuggestionOutcome,
  Ticket,
  Timeline,
  TimelineAttachment,
  TimelineCommentEntry,
  TimelineEntry,
  TimelineEventEntry,
  TimelineTaskEntry,
  TimeSummary,
} from './resources/types.js';
