import type { ChangeContent } from '../plan/content-types.js';

/**
 * The 42 changes, `CHG-1151` … `CHG-1192`, in number order (A4 §1.9.2).
 *
 * - 30 closed in the window: 18 standard (patching, drivers, sandbox
 *   refreshes, the scanner OS), 10 normal (one backed out: the Leeds core
 *   switch firmware) and 2 emergency (the Leeds failover during MI-0001 and
 *   the Salesforce certificate during MI-0003).
 * - 3 scheduled this week, two of them published as maintenance windows on the
 *   status page; 4 standard changes in the next two weeks.
 * - 2 awaiting the CAB — Jordan Lee's two approvals — one of them planned
 *   inside the month-end blackout, so the clash warning shows.
 * - 2 drafts, and CHG-1192, the emergency change the live incident raised.
 *
 * Numbers follow the order the changes were raised, so the closed ones run
 * oldest first. Times are local and inside the change windows (weekday
 * evenings 18:00–22:00, Saturdays 08:00–18:00) except the two emergencies,
 * which happened when their incidents did.
 */
export const CHANGES = [
  /* ---------------------------------------------- Closed in the window */
  {
    number: 1151,
    title: 'Monthly laptop patching — pilot group',
    description: 'This month’s Windows and Microsoft 365 Apps updates to the 25 pilot laptops in IT and Finance, a week ahead of everyone else.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'euc',
    owner: 'sofia-rossi',
    service: 'end-user-devices',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 115, start: '18:30', minutes: 90 },
    implementationPlan: 'Release the updates to the pilot ring in Intune; check the compliance report the next morning.',
    backoutPlan: 'Pause the ring and uninstall the update from affected laptops through Intune.',
  },
  {
    number: 1152,
    title: 'Salesforce sandbox refresh',
    description: 'Refresh the full-copy sandbox from production so the sales operations team can test the new territory rules on current data.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'bizapps',
    owner: 'hannah-becker',
    service: 'salesforce',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 110, start: '18:00', minutes: 120 },
  },
  {
    number: 1153,
    title: 'Add the Bristol hub to the guest Wi-Fi captive portal',
    description: 'Bristol visitors currently get the old shared guest password. Move the Bristol access points onto the same captive portal as London and Leeds, with codes printed at reception.',
    kind: 'normal',
    risk: 'medium',
    impact: 'low',
    team: 'network',
    owner: 'aisha-rahman',
    service: 'network-vpn',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 106, start: '18:30', minutes: 90 },
    implementationPlan: 'Assign the Bristol access points to the guest portal policy in the Meraki dashboard; test a printed code from reception.',
    backoutPlan: 'Return the Bristol access points to their previous SSID policy.',
  },
  {
    number: 1154,
    title: 'Monthly server patching — Leeds file and WMS servers',
    description: 'This month’s Windows Server updates to lds-fs01 and lds-wms-db01, after the late picking shift has finished.',
    kind: 'standard',
    risk: 'low',
    impact: 'medium',
    team: 'network',
    owner: 'aisha-rahman',
    service: 'warehouse-wms',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 101, start: '19:00', minutes: 180 },
  },
  {
    number: 1155,
    title: 'Ricoh universal print driver update',
    description: 'Deploy the current Ricoh universal print driver to every laptop, which fixes duplex printing from Excel.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'euc',
    owner: 'ben-carter',
    service: 'printing',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 97, start: '18:00', minutes: 60 },
  },
  {
    number: 1156,
    title: 'Turn on number matching for Authenticator sign-ins',
    description: 'Require people to type the number shown on screen when they approve a sign-in, so an approval prompt nobody asked for can’t simply be tapped through.',
    kind: 'normal',
    risk: 'medium',
    impact: 'medium',
    team: 'identity',
    owner: 'chloe-nguyen',
    service: 'identity-access',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 92, start: '18:00', minutes: 60 },
    implementationPlan: 'Enable number matching in the Entra ID authentication methods policy for all users; all-staff email sent two days before.',
    backoutPlan: 'Switch the setting back off in the authentication methods policy.',
  },
  {
    number: 1157,
    title: 'Monthly laptop patching — all laptops',
    description: 'This month’s Windows and Microsoft 365 Apps updates to every laptop, after a clean week on the pilot group.',
    kind: 'standard',
    risk: 'low',
    impact: 'medium',
    team: 'euc',
    owner: 'sofia-rossi',
    service: 'end-user-devices',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 88, start: '18:00', minutes: 240 },
  },
  {
    number: 1158,
    title: 'Salesforce seasonal release: regression checks',
    description: 'Run the regression checklist against the sandbox before Salesforce’s seasonal release reaches production, and switch on the two new features sales operations asked for.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'bizapps',
    owner: 'hannah-becker',
    service: 'salesforce',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 84, start: '18:00', minutes: 120 },
  },
  {
    number: 1159,
    title: 'BambooHR single sign-on through Entra ID',
    description: 'Replace BambooHR passwords with single sign-on through Entra ID, so leavers lose access the moment their account is disabled.',
    kind: 'normal',
    risk: 'medium',
    impact: 'medium',
    team: 'identity',
    owner: 'ryan-webb',
    service: 'hr-systems',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 79, start: '18:30', minutes: 90 },
    implementationPlan: 'Configure the enterprise application in Entra ID, assign all staff, then turn on SSO in BambooHR; test with three HR users.',
    backoutPlan: 'Turn SSO off in BambooHR; password sign-in comes back for everyone.',
  },
  {
    number: 1160,
    title: 'Zebra TC58 scanner OS update — aisles 1–9',
    description: 'Update the handheld scanners used in aisles 1 to 9 to the current Android release through Zebra MDM, between shifts.',
    kind: 'standard',
    risk: 'low',
    impact: 'medium',
    team: 'euc',
    owner: 'ben-carter',
    service: 'warehouse-wms',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 74, start: '19:00', minutes: 180 },
  },
  {
    number: 1161,
    title: 'Monthly server patching — print server ldn-print01',
    description: 'This month’s Windows Server updates to the London print server.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'network',
    owner: 'aisha-rahman',
    service: 'printing',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 70, start: '18:30', minutes: 60 },
  },
  {
    number: 1162,
    title: 'Enrol new laptops with Windows Autopilot',
    description: 'New laptops ship from Dell registered to Northwind and set themselves up when the new starter signs in, instead of being imaged by hand.',
    kind: 'normal',
    risk: 'medium',
    impact: 'medium',
    team: 'euc',
    owner: 'ben-carter',
    service: 'end-user-devices',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 66, start: '18:00', minutes: 120 },
    implementationPlan: 'Import the hardware IDs from Dell, assign the Autopilot profile and test with two new laptops.',
    backoutPlan: 'Remove the profile assignment; laptops fall back to the manual image.',
  },
  {
    number: 1163,
    title: 'Fail Leeds over to the 4G backup router',
    description: 'Emergency change during MI-0001: the BT circuit into Leeds is cut. Move the site’s traffic to the 4G backup router so the WMS and the scanners can reach the database again.',
    kind: 'emergency',
    risk: 'high',
    impact: 'high',
    team: 'network',
    owner: 'daniel-hughes',
    service: 'network-vpn',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 61, start: '11:05', minutes: 45 },
    majorIncident: 1,
    problem: 416,
    implementationPlan: 'Change the default route on the Leeds edge router to the 4G backup; check the WMS from a scanner on the warehouse floor.',
    backoutPlan: 'Restore the default route to the BT circuit once BT confirm the repair.',
  },
  {
    number: 1164,
    title: 'Automatic failover to the 4G backup for the Leeds site link',
    description: 'Action from the MI-0001 review: add the 4G backup router to the SD-WAN policy so Leeds fails over by itself when the BT circuit drops.',
    kind: 'normal',
    risk: 'medium',
    impact: 'high',
    team: 'network',
    owner: 'daniel-hughes',
    service: 'network-vpn',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 57, start: '19:00', minutes: 120 },
    problem: 416,
    implementationPlan: 'Add the backup link to the Leeds SD-WAN policy; pull the BT circuit’s cable for five minutes and confirm the WMS stays up.',
    backoutPlan: 'Remove the backup link from the policy; failover returns to manual.',
  },
  {
    number: 1165,
    title: 'Monthly laptop patching — pilot group',
    description: 'This month’s Windows and Microsoft 365 Apps updates to the 25 pilot laptops in IT and Finance, a week ahead of everyone else.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'euc',
    owner: 'sofia-rossi',
    service: 'end-user-devices',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 53, start: '18:30', minutes: 90 },
  },
  {
    number: 1166,
    title: 'Windows 11 24H2 laptop image — rollout',
    description: 'Move every laptop to the Windows 11 24H2 image over two weeks, a floor at a time, starting with London.',
    kind: 'normal',
    risk: 'medium',
    impact: 'high',
    team: 'euc',
    owner: 'ben-carter',
    service: 'end-user-devices',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 50, start: '18:00', minutes: 180 },
    implementationPlan: 'Release the feature update to one floor per evening through Intune; the Service Desk keeps an extra person on the early shift the morning after each wave.',
    backoutPlan: 'Roll a laptop back to the previous version within ten days from Windows recovery settings.',
  },
  {
    number: 1167,
    title: 'Microsoft 365 Apps monthly channel update',
    description: 'Move Microsoft 365 Apps on every laptop to this month’s build.',
    kind: 'standard',
    risk: 'low',
    impact: 'medium',
    team: 'euc',
    owner: 'sofia-rossi',
    service: 'microsoft-365',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 47, start: '18:00', minutes: 60 },
  },
  {
    number: 1168,
    title: 'Leeds core switch firmware 17.9',
    description: 'Upgrade the two core switches at the Leeds Distribution Centre to firmware 17.9, which fixes the memory leak behind last quarter’s unplanned reboots.',
    kind: 'normal',
    risk: 'medium',
    impact: 'high',
    team: 'network',
    owner: 'daniel-hughes',
    service: 'network-vpn',
    state: 'closed',
    closeCode: 'backed_out',
    when: { kind: 'past', daysBeforeT0: 44, start: '19:00', minutes: 180 },
    implementationPlan: 'Upgrade the standby switch first, fail over, then upgrade the primary; test the WMS from a scanner after each step.',
    backoutPlan:
      'Boot the switch from the previous firmware image. (Used: after the upgrade the standby switch did not rejoin the stack, so both were returned to 17.6 by 21:40 and the upgrade will be rescheduled with the vendor.)',
  },
  {
    number: 1169,
    title: 'Monthly server patching — Leeds file and WMS servers',
    description: 'This month’s Windows Server updates to lds-fs01 and lds-wms-db01, after the late picking shift has finished.',
    kind: 'standard',
    risk: 'low',
    impact: 'medium',
    team: 'network',
    owner: 'aisha-rahman',
    service: 'warehouse-wms',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 40, start: '19:00', minutes: 180 },
  },
  {
    number: 1170,
    title: 'Salesforce sandbox refresh',
    description: 'Refresh the full-copy sandbox from production before the next round of report changes.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'bizapps',
    owner: 'hannah-becker',
    service: 'salesforce',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 37, start: '18:00', minutes: 120 },
  },
  {
    number: 1171,
    title: 'Raise the Sage Intacct bank export time limit',
    description: 'Fix for PRB-0414: raise the bank export report’s time limit and split the export by supplier group, so month-end volumes no longer time out.',
    kind: 'normal',
    risk: 'medium',
    impact: 'high',
    team: 'bizapps',
    owner: 'liam-walsh',
    service: 'finance-systems',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 30, start: '18:30', minutes: 60 },
    problem: 414,
    implementationPlan: 'Change the report’s limit to 900 seconds and add the supplier-group split; run a test export of last month’s volume in the sandbox first.',
    backoutPlan: 'Restore the previous report definition from the saved copy.',
  },
  {
    number: 1172,
    title: 'Monthly laptop patching — all laptops',
    description: 'This month’s Windows and Microsoft 365 Apps updates to every laptop, after a clean week on the pilot group.',
    kind: 'standard',
    risk: 'low',
    impact: 'medium',
    team: 'euc',
    owner: 'sofia-rossi',
    service: 'end-user-devices',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 27, start: '18:00', minutes: 240 },
  },
  {
    number: 1173,
    title: 'Driver update for the Leeds goods-in printers',
    description: 'New driver for the two goods-in label printers, which stops delivery notes printing on two labels.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'euc',
    owner: 'ben-carter',
    service: 'printing',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 24, start: '18:00', minutes: 60 },
  },
  {
    number: 1174,
    title: 'Dell WD19S dock firmware 01.00.32 — first desks',
    description: 'Fix for PRB-0412: update the dock firmware on the first 60 desks in London, starting with the people who reported black screens after wake.',
    kind: 'normal',
    risk: 'medium',
    impact: 'medium',
    team: 'euc',
    owner: 'ben-carter',
    service: 'end-user-devices',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 20, start: '18:00', minutes: 120 },
    problem: 412,
    implementationPlan: 'Push the firmware with Dell Command | Update to the selected docks while they are connected; check each dock’s version the next morning.',
    backoutPlan: 'The firmware cannot be rolled back on the dock; swap any dock that fails for a spare.',
  },
  {
    number: 1175,
    title: 'Monthly server patching — print server ldn-print01',
    description: 'This month’s Windows Server updates to the London print server.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'network',
    owner: 'aisha-rahman',
    service: 'printing',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 16, start: '18:30', minutes: 60 },
  },
  {
    number: 1176,
    title: 'Renew the Salesforce SSO signing certificate',
    description: 'Emergency change during MI-0003: the SAML signing certificate has expired and nobody can sign in to Salesforce. Issue a new one in Entra ID and upload it to Salesforce.',
    kind: 'emergency',
    risk: 'high',
    impact: 'high',
    team: 'identity',
    owner: 'chloe-nguyen',
    service: 'salesforce',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 12, start: '09:35', minutes: 20 },
    majorIncident: 3,
    problem: 417,
    implementationPlan: 'Create a new signing certificate on the Salesforce enterprise application, upload it in Salesforce’s single sign-on settings, test with the sales team.',
    backoutPlan: 'None needed: the expired certificate cannot be restored.',
  },
  {
    number: 1177,
    title: 'Salesforce: add the promotions dashboard to the reporting workspace',
    description: 'Publish the promotions performance dashboard to the reporting workspace for the trade marketing team.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'bizapps',
    owner: 'hannah-becker',
    service: 'salesforce',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 9, start: '18:00', minutes: 60 },
  },
  {
    number: 1178,
    title: 'Monthly laptop patching — pilot group',
    description: 'This month’s Windows and Microsoft 365 Apps updates to the 25 pilot laptops in IT and Finance, a week ahead of everyone else.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'euc',
    owner: 'sofia-rossi',
    service: 'end-user-devices',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 6, start: '18:30', minutes: 90 },
  },
  {
    number: 1179,
    title: 'Move the Bristol hub printers to the London print server',
    description: 'Bristol’s three printers still print through an old local server. Move their queues to ldn-print01 so they get the same drivers and Follow-Me printing as London.',
    kind: 'normal',
    risk: 'low',
    impact: 'medium',
    team: 'euc',
    owner: 'ben-carter',
    service: 'printing',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 4, start: '18:00', minutes: 120 },
    implementationPlan: 'Create the three queues on ldn-print01, push them to Bristol laptops through Intune, then remove the old queues.',
    backoutPlan: 'Re-deploy the old queues from the Bristol server, which stays switched on for two weeks.',
  },
  {
    number: 1180,
    title: 'Monthly server patching — London SQL server ldn-sql02',
    description: 'This month’s Windows Server and SQL Server updates to ldn-sql02, which holds the finance reporting databases.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'network',
    owner: 'aisha-rahman',
    service: 'finance-systems',
    state: 'closed',
    closeCode: 'successful',
    when: { kind: 'past', daysBeforeT0: 2, start: '19:00', minutes: 90 },
  },

  /* ---------------------------------------------- Scheduled this week */
  {
    number: 1181,
    title: 'Firewall firmware 9.1.4 — Leeds',
    description: 'Upgrade the Leeds firewall pair to 9.1.4, which the vendor lists as a security release. The Leeds site will lose internet access for up to ten minutes during the swap-over.',
    kind: 'normal',
    risk: 'medium',
    impact: 'high',
    team: 'network',
    owner: 'daniel-hughes',
    service: 'network-vpn',
    state: 'scheduled',
    when: { kind: 'week', weekday: 'wed', weeksAhead: 0, start: '19:00', minutes: 120 },
    maintenanceWindow: true,
    implementationPlan: 'Upgrade the passive firewall, fail over, upgrade the active one, fail back; check the WMS, VPN and internet access from Leeds after each step.',
    backoutPlan: 'Boot each firewall from its previous firmware partition.',
  },
  {
    number: 1182,
    title: 'Sage Intacct 2026 R4 upgrade',
    description: 'Sage’s quarterly release for Northwind’s Sage Intacct company. Sage Intacct will be unavailable while it runs; Finance have agreed the Saturday morning.',
    kind: 'normal',
    risk: 'medium',
    impact: 'high',
    team: 'bizapps',
    owner: 'liam-walsh',
    service: 'finance-systems',
    state: 'scheduled',
    when: { kind: 'week', weekday: 'sat', weeksAhead: 0, start: '08:00', minutes: 240 },
    maintenanceWindow: true,
    implementationPlan: 'Sage apply the release; Business Applications run the finance smoke tests (journals, the bank file, the supplier payment run) before handing back.',
    backoutPlan: 'Sage restore the company from the snapshot taken at 07:45.',
  },
  {
    number: 1183,
    title: 'Wi-Fi access point replacement — London 4th floor',
    description: 'Fix for PRB-0415: replace the six 4th-floor access points with current models and re-plan the channels, so laptops stop dropping Teams calls as they move between rooms.',
    kind: 'normal',
    risk: 'medium',
    impact: 'medium',
    team: 'network',
    owner: 'daniel-hughes',
    service: 'network-vpn',
    state: 'scheduled',
    when: { kind: 'week', weekday: 'thu', weeksAhead: 0, start: '18:30', minutes: 150 },
    problem: 415,
    implementationPlan: 'Swap ap-ldn-4f-01 to 06 one at a time, adopt them in the Meraki dashboard and run a walking Teams call through 4.02 and 4.05.',
    backoutPlan: 'Re-mount the old access points, which stay on site for a week.',
  },

  /* ---------------------------------------------- Scheduled in the next two weeks */
  {
    number: 1184,
    title: 'Monthly laptop patching — all laptops',
    description: 'This month’s Windows and Microsoft 365 Apps updates to every laptop, after a clean week on the pilot group.',
    kind: 'standard',
    risk: 'low',
    impact: 'medium',
    team: 'euc',
    owner: 'sofia-rossi',
    service: 'end-user-devices',
    state: 'scheduled',
    when: { kind: 'week', weekday: 'tue', weeksAhead: 1, start: '18:00', minutes: 240 },
  },
  {
    number: 1185,
    title: 'Salesforce sandbox refresh',
    description: 'Refresh the full-copy sandbox from production for the next set of report changes.',
    kind: 'standard',
    risk: 'low',
    impact: 'low',
    team: 'bizapps',
    owner: 'hannah-becker',
    service: 'salesforce',
    state: 'scheduled',
    when: { kind: 'week', weekday: 'wed', weeksAhead: 1, start: '18:00', minutes: 120 },
  },
  {
    number: 1186,
    title: 'Zebra TC58 scanner OS update — aisles 10–14',
    description: 'Update the handheld scanners used in aisles 10 to 14 to the same Android release as the rest of the warehouse.',
    kind: 'standard',
    risk: 'low',
    impact: 'medium',
    team: 'euc',
    owner: 'ben-carter',
    service: 'warehouse-wms',
    state: 'scheduled',
    when: { kind: 'week', weekday: 'sat', weeksAhead: 2, start: '08:00', minutes: 240 },
  },
  {
    number: 1187,
    title: 'Monthly server patching — Leeds file and WMS servers',
    description: 'This month’s Windows Server updates to lds-fs01 and lds-wms-db01, after the late picking shift has finished.',
    kind: 'standard',
    risk: 'low',
    impact: 'medium',
    team: 'network',
    owner: 'aisha-rahman',
    service: 'warehouse-wms',
    state: 'scheduled',
    when: { kind: 'week', weekday: 'thu', weeksAhead: 2, start: '19:00', minutes: 180 },
  },

  /* ---------------------------------------------- Awaiting the CAB (Jordan Lee) */
  {
    number: 1188,
    title: 'Guest Wi-Fi segmentation — London',
    description: 'Put London guest Wi-Fi on its own network segment with internet access only, so a visitor’s laptop can never see the printers or the meeting-room consoles.',
    kind: 'normal',
    risk: 'medium',
    impact: 'medium',
    team: 'network',
    owner: 'daniel-hughes',
    service: 'network-vpn',
    state: 'submitted',
    when: { kind: 'week', weekday: 'tue', weeksAhead: 0, start: '19:00', minutes: 120 },
    implementationPlan: 'Create the guest VLAN on the London core and firewall, move the guest SSID onto it, and test from a guest code at reception.',
    backoutPlan: 'Move the guest SSID back to its current VLAN.',
  },
  {
    number: 1189,
    title: 'Move the WMS database to the new SQL cluster',
    description: 'Move the warehouse management database from lds-wms-db01 to the new two-node SQL cluster, so a server failure no longer stops picking. The WMS is down while the database is copied.',
    kind: 'normal',
    risk: 'high',
    impact: 'high',
    team: 'bizapps',
    owner: 'liam-walsh',
    service: 'warehouse-wms',
    state: 'submitted',
    when: { kind: 'blackout', start: '18:00', minutes: 240 },
    implementationPlan: 'Stop the WMS services, back up and restore the database to the cluster, repoint the application and test picking with the late-shift supervisor.',
    backoutPlan: 'Repoint the WMS at lds-wms-db01, which is left untouched until the next morning.',
  },

  /* ---------------------------------------------- Drafts */
  {
    number: 1190,
    title: 'Retire the old Ricoh printers',
    description: 'Remove the eight old Ricoh printers once the new Follow-Me printers are in on every floor, and take their queues off the print server.',
    kind: 'normal',
    risk: 'low',
    impact: 'low',
    team: 'euc',
    owner: 'ben-carter',
    service: 'printing',
    state: 'draft',
    when: { kind: 'unscheduled' },
  },
  {
    number: 1191,
    title: 'Renew the BT SD-WAN contract terms',
    description: 'Move the Leeds and Bristol circuits onto the renewed BT SD-WAN terms, including the faster repair times agreed after MI-0001.',
    kind: 'normal',
    risk: 'low',
    impact: 'low',
    team: 'network',
    owner: 'daniel-hughes',
    service: 'network-vpn',
    state: 'draft',
    when: { kind: 'unscheduled' },
  },

  /* ---------------------------------------------- The live incident's emergency change */
  {
    number: 1192,
    title: 'Reissue the VPN gateway intermediate certificate',
    description: 'Emergency change for MI-0004: the new intermediate certificate on both VPN gateways is missing from the chain sent to clients, so laptops refuse it. Reissue it with the full chain on vpn-gw-ldn-01, then vpn-gw-ldn-02.',
    kind: 'emergency',
    risk: 'high',
    impact: 'high',
    team: 'network',
    owner: 'daniel-hughes',
    service: 'network-vpn',
    state: 'implementing',
    when: { kind: 'live' },
    majorIncident: 4,
    problem: 418,
    implementationPlan: 'Reissue the certificate with the full chain on vpn-gw-ldn-01, test with three remote users, then repeat on vpn-gw-ldn-02.',
    backoutPlan: 'Restore the previous certificate from the gateway’s backup; remote staff fall back to the workaround article.',
  },
] satisfies readonly ChangeContent[];
