import type { RichBlock, RichInline } from '@itsm/contracts/forms';
import type { KnowledgeArticleContent } from '../plan/content-types.js';

/**
 * Northwind's knowledge base (A4 §1.5): 24 published articles — 18 for all
 * staff and six internal runbooks — plus one draft and one in review.
 *
 * Eight are reused verbatim from the portal's design seed (`reused: true`), so
 * the Help Portal reads in the voice it was designed with; only the company's
 * own names change (the Wi-Fi networks are Northwind's, not the old seed
 * company's). The other eighteen are written for the story: the live
 * incident's workaround, the dock firmware problem's known-error article, the
 * runbooks the Service Desk works from.
 *
 * Bodies are structured blocks, never HTML, and every link is `mailto:` to a
 * `northwind.example` address (D23: links are `https:` or `mailto:` only, and
 * a demo article must not send a visitor to a real site).
 */

type Part = string | RichInline;

const inline = (part: Part): RichInline => (typeof part === 'string' ? { text: part } : part);
const p = (...parts: Part[]): RichBlock => ({ type: 'paragraph', content: parts.map(inline) });
const steps = (...items: (Part | Part[])[]): RichBlock => ({
  type: 'list',
  ordered: true,
  items: items.map((item) => (Array.isArray(item) ? item.map(inline) : [inline(item)])),
});
const bullets = (...items: (Part | Part[])[]): RichBlock => ({
  type: 'list',
  items: items.map((item) => (Array.isArray(item) ? item.map(inline) : [inline(item)])),
});
const bold = (text: string): RichInline => ({ text, bold: true });
const mail = (address: string): RichInline => ({ text: address, href: `mailto:${address}` });

export const KNOWLEDGE = [
  /* ---------------------------------------------- How-to (all staff) */
  {
    key: 'email-on-phone',
    title: 'Set up work email on your phone',
    summary: 'Outlook for iPhone or Android, with your calendar and contacts.',
    category: 'how-to',
    audience: 'all',
    state: 'published',
    views: 188,
    helpfulPercent: 91,
    publishedDaysAgo: 120,
    keywords: ['email', 'phone', 'iphone', 'android', 'outlook', 'calendar'],
    service: 'microsoft-365',
    reused: true,
    body: [
      p('Use the Outlook app rather than the phone’s own Mail app: it keeps work email separate and is the only app that can open protected messages.'),
      steps('Install Microsoft Outlook from the App Store or Google Play.', 'Open it and enter your work email address.', 'Approve the sign-in in the Authenticator app.', 'Allow notifications when it asks, so meeting reminders reach you.'),
      p('Invites not showing up? Remove the account from the app and add it again — it takes a minute and fixes most sync problems.'),
    ],
  },
  {
    key: 'office-wifi',
    title: 'Connect to the office Wi-Fi',
    summary: 'Which network to choose, and how guests get online.',
    category: 'how-to',
    audience: 'all',
    state: 'published',
    views: 164,
    helpfulPercent: 86,
    publishedDaysAgo: 201,
    keywords: ['wifi', 'wi-fi', 'wireless', 'guest', 'network'],
    service: 'network-vpn',
    reused: true,
    body: [
      p('Company laptops join “Northwind-Corp” by themselves. Phones and personal devices use “Northwind-Staff”, which asks for your work email and password once.'),
      bullets('Northwind-Corp: company laptops only, connected automatically.', 'Northwind-Staff: your phone or tablet.', 'Northwind-Guest: visitors. Reception prints a code that lasts one day.'),
      p('If a company laptop shows “No internet” on Northwind-Corp, restart it once while plugged into the dock so it can renew its certificate.'),
    ],
  },
  {
    key: 'vpn-from-home',
    title: 'Connect to the VPN from home',
    summary: 'Connect to the office network from home in three steps.',
    category: 'how-to',
    audience: 'all',
    state: 'published',
    views: 412,
    helpfulPercent: 89,
    publishedDaysAgo: 201,
    keywords: ['vpn', 'remote', 'home', 'working from home'],
    service: 'network-vpn',
    reused: true,
    body: [
      p('The VPN lets you reach internal systems — the finance ledger, HR records and the intranet — from anywhere. You need it whenever you work away from the office.'),
      steps(['Open ', bold('Company Portal'), ' and install the VPN client.'], 'Sign in with your work account when it asks.', ['Choose ', bold('Connect'), '. A key appears in the menu bar when you are on.']),
      p('If the client says your certificate has expired, restart your laptop while connected to the office Wi-Fi once, and it will renew itself.'),
      p('Still stuck? Report an issue and mention the error message you saw.'),
    ],
  },
  {
    key: 'meeting-room-screens',
    title: 'Use the meeting-room screens',
    summary: 'Join a meeting and share your laptop on the big screen in Thames, Severn, Aire or Avon.',
    category: 'how-to',
    audience: 'all',
    state: 'published',
    views: 96,
    helpfulPercent: 84,
    publishedDaysAgo: 150,
    keywords: ['meeting room', 'screen', 'display', 'teams room', 'hdmi', 'no signal', 'thames', 'severn', 'aire', 'avon'],
    service: 'microsoft-365',
    body: [
      p('Every bookable meeting room — Thames, Severn, Aire and Avon — has a screen with a Teams Rooms console on the table. You can join the meeting from the console or share straight from your laptop.'),
      steps(
        ['Tap ', bold('Join'), ' on the console next to your meeting. It lists the room’s bookings for today.'],
        'To share, plug the USB-C cable on the table into your laptop. The screen switches over by itself within a few seconds.',
        ['No cable? In your Teams meeting choose ', bold('Share'), ', then pick the room’s screen.'],
      ),
      p('If the screen says “No signal”, unplug the cable, wait five seconds and plug it in again. Still nothing? Call the service desk on extension 4000 — someone can usually reach the room within ten minutes.'),
    ],
  },
  {
    key: 'authenticator-new-phone',
    title: 'Set up Microsoft Authenticator on a new phone',
    summary: 'Move your sign-in approvals to a new phone before you hand the old one back.',
    category: 'how-to',
    audience: 'all',
    state: 'published',
    views: 351,
    helpfulPercent: 90,
    publishedDaysAgo: 175,
    keywords: ['authenticator', 'mfa', 'multi-factor', 'new phone', 'sign-in', 'approval'],
    service: 'identity-access',
    body: [
      p('Microsoft Authenticator is how you approve sign-ins to your work account. It belongs to one phone at a time, so move it before your old phone goes back to IT.'),
      steps(
        'On your new phone, install Microsoft Authenticator from the App Store or Google Play.',
        ['On your laptop, open your account’s security info page (search for ', bold('My Sign-Ins'), ' in the Start menu) and choose ', bold('Add sign-in method'), ' › Authenticator app.'],
        'Scan the QR code with the new phone and approve the test notification.',
        'Make the new phone your default sign-in method, then delete the old one from the list.',
      ),
      p('Already handed the old phone back, or lost it? Request “Reset multi-factor sign-in” in the service catalogue. We’ll call your desk number first to check it’s you.'),
    ],
  },
  {
    key: 'share-securely',
    title: 'Share a file securely outside Northwind',
    summary: 'Send a OneDrive link that only the right person can open, and that switches itself off.',
    category: 'how-to',
    audience: 'all',
    state: 'published',
    views: 77,
    helpfulPercent: 82,
    publishedDaysAgo: 230,
    keywords: ['share', 'onedrive', 'sharepoint', 'external', 'link', 'secure', 'customer', 'supplier'],
    service: 'microsoft-365',
    body: [
      p('Never email a spreadsheet of customer or staff details as an attachment. Share a link instead: you can see who opened it and switch it off later.'),
      steps(
        ['In OneDrive or SharePoint, select the file and choose ', bold('Share'), '.'],
        'Choose “Specific people” and type the recipient’s email address.',
        'Set an expiry date — 30 days is usually right — and turn off editing unless they need it.',
        'Send. They receive a one-time code by email to open the file.',
      ),
      p('Not sure whether something is safe to share? Ask first: ', mail('security@northwind.example'), '.'),
    ],
  },
  {
    key: 'shared-mailbox-howto',
    title: 'Ask for access to a shared mailbox',
    summary: 'Get access to a team mailbox such as finance@, and find it in Outlook.',
    category: 'how-to',
    audience: 'all',
    state: 'published',
    views: 140,
    helpfulPercent: 87,
    publishedDaysAgo: 96,
    keywords: ['shared mailbox', 'mailbox', 'finance@', 'team mailbox', 'outlook', 'access'],
    service: 'microsoft-365',
    body: [
      p('Team mailboxes such as finance@northwind.example and customerservice@northwind.example each belong to a manager, who approves who can read and send from them.'),
      steps(
        'In the service catalogue, choose “Access to a shared mailbox”.',
        'Enter the mailbox address, and say whether you need to read it or also send as it.',
        'Your request goes to your line manager to approve. Once they have, it is usually set up within the hour.',
      ),
      p('The mailbox appears in Outlook by itself the next time you open it — allow up to an hour. If it doesn’t, close Outlook completely and open it again, then reply to your request if it’s still missing.'),
    ],
  },
  {
    key: 'out-of-office',
    title: 'Set your out-of-office in Outlook',
    summary: 'From your laptop, webmail or phone, with a different reply for people outside Northwind.',
    category: 'how-to',
    audience: 'all',
    state: 'published',
    views: 233,
    helpfulPercent: 93,
    publishedDaysAgo: 262,
    keywords: ['out of office', 'automatic reply', 'holiday', 'leave', 'outlook', 'phone'],
    service: 'microsoft-365',
    body: [
      p('Set an automatic reply before you go on leave, so people know who to contact instead.'),
      bullets(
        ['On your laptop: in Outlook choose ', bold('File'), ' › Automatic Replies.'],
        ['In webmail: ', bold('Settings'), ' › Mail › Automatic replies.'],
        'On your phone: in the Outlook app, tap your initials, then the settings cog, then your account › Automatic replies.',
      ),
      p('Turn on “Only send during this time range” and set your return date, so it switches itself off. You can write a shorter message for people outside Northwind — there’s no need to tell customers where you are.'),
    ],
  },

  /* ---------------------------------------------- Troubleshooting (all staff) */
  {
    key: 'outlook-password-prompt',
    title: 'Outlook keeps asking for your password',
    summary: 'Usually an old saved password after a change. Two minutes to fix.',
    category: 'troubleshooting',
    audience: 'all',
    state: 'published',
    views: 241,
    helpfulPercent: 88,
    publishedDaysAgo: 44,
    keywords: ['outlook', 'password', 'prompt', 'credential'],
    service: 'microsoft-365',
    reused: true,
    body: [
      p('If Outlook asks for your password every few minutes, it is almost always holding on to the password you used before your last change.'),
      steps('Close Outlook.', 'Open Credential Manager from the Start menu and choose Windows Credentials.', 'Remove every entry that starts with “MicrosoftOffice16”.', 'Open Outlook again and sign in once when it asks.'),
      p('If the prompt comes back only when your laptop is on the dock, report an issue and say so: that points to the office network rather than your laptop.'),
    ],
  },
  {
    key: 'printer-offline',
    title: 'Printer shows as offline',
    summary: 'What to try before reporting it, and what to tell us if it’s still off.',
    category: 'troubleshooting',
    audience: 'all',
    state: 'published',
    views: 97,
    helpfulPercent: 80,
    publishedDaysAgo: 63,
    keywords: ['printer', 'print', 'offline', 'ricoh'],
    service: 'printing',
    reused: true,
    body: [
      p('Most “offline” printers are fine — it’s the laptop that has lost track of them after moving between floors.'),
      steps('Open Settings › Printers & scanners and remove the printer.', 'Choose Add device and pick it again from the list (the name is on a label on the front, like PRN-3F-01).', 'Print a test page.'),
      p('If it still says offline, report an issue with the printer’s name and whether colleagues can print to it.'),
    ],
  },
  {
    key: 'mapped-drive-missing',
    title: 'A shared drive is missing after an update',
    summary: 'Get S: and the team drives back without waiting for us.',
    category: 'troubleshooting',
    audience: 'all',
    state: 'published',
    views: 72,
    helpfulPercent: 79,
    publishedDaysAgo: 15,
    keywords: ['s drive', 'shared drive', 'mapped', 'share', 'update'],
    service: 'microsoft-365',
    reused: true,
    body: [
      p('Drives such as S: are connected each time you sign in, but only when your laptop can see the office network.'),
      steps('Connect to the office network or the VPN.', 'Restart your laptop and sign in.', 'Open File Explorer: the drive should be back under This PC.'),
      p('Still missing after a restart on the office network? Report an issue and tell us the drive letter.'),
    ],
  },
  {
    key: 'vpn-authentication-failed',
    title: 'Connect to the VPN when it says ‘Authentication failed’',
    summary: 'A known problem with the VPN certificate. Three steps get most people connected while we fix it.',
    category: 'troubleshooting',
    audience: 'all',
    state: 'published',
    views: { day: 37, night: 84 },
    helpfulPercent: 81,
    publishedDaysAgo: 0,
    keywords: ['vpn', 'authentication failed', 'remote', 'certificate', 'mi-0004', 'cannot connect'],
    service: 'network-vpn',
    body: [
      p('We know about this. A certificate on the VPN gateways was changed and some laptops are refusing the new one. You don’t need to restart your laptop or reset your password.'),
      steps(
        'Disconnect, then sign out of the VPN client.',
        'Open Microsoft Authenticator and approve the pending request.',
        ['Connect again and choose ', bold('Northwind-Remote-2'), '.'],
      ),
      p('If it still fails, you don’t need to raise a ticket — we’re already working on it. Follow MI-0004 on the status page.'),
    ],
  },
  {
    key: 'dock-black-screen',
    title: 'Laptop won’t wake from sleep when docked',
    summary: 'Black screens after the laptop sleeps on a Dell WD19S dock: the quick fix, and the permanent one.',
    category: 'troubleshooting',
    audience: 'all',
    state: 'published',
    views: 268,
    helpfulPercent: 92,
    publishedDaysAgo: 44,
    keywords: ['dock', 'black screen', 'sleep', 'wake', 'wd19s', 'monitor', 'dell', 'prb-0412'],
    service: 'end-user-devices',
    body: [
      p('This is a known problem with the firmware on some Dell WD19S docks: the laptop wakes up, but the dock doesn’t pass the picture on to your screens. Holding the power button works, but you lose anything you hadn’t saved.'),
      steps(
        'Unplug the dock’s USB-C cable from your laptop.',
        'Wait until the laptop’s own screen comes on, then plug the cable back in.',
        ['If the screens are still black, press ', bold('Windows key + P'), ' and choose Extend.'],
      ),
      p('The permanent fix is a firmware update for the dock, which we’re rolling out desk by desk. If yours still does this, report an issue with the asset tag from the bottom of your laptop and we’ll update your dock first.'),
    ],
  },
  {
    key: 'teams-camera',
    title: 'Teams camera or microphone not detected',
    summary: 'When Teams says it can’t find your camera or microphone, usually after an update.',
    category: 'troubleshooting',
    audience: 'all',
    state: 'published',
    views: 154,
    helpfulPercent: 85,
    publishedDaysAgo: 41,
    keywords: ['teams', 'camera', 'webcam', 'microphone', 'not detected', 'video', 'call'],
    service: 'microsoft-365',
    body: [
      p('Teams can only use a camera or microphone that no other app is holding on to, and that Windows lets it use.'),
      steps(
        'Close any other app that might be using the camera, such as the Windows Camera app or a browser tab with a video call.',
        ['In Teams, open ', bold('Settings'), ' › Devices and choose the right camera and microphone from the lists.'],
        'In Windows Settings › Privacy & security › Camera (and then Microphone), make sure “Let desktop apps access your camera” is on.',
        'Quit Teams completely — right-click its icon by the clock and choose Quit — then open it again.',
      ),
      p('Still not detected? Report an issue and say whether the camera works in the Windows Camera app: that tells us whether it’s Teams or the driver.'),
    ],
  },
  {
    key: 'onedrive-sync-paused',
    title: 'OneDrive says “Sync paused”',
    summary: 'Get OneDrive syncing again, and check nothing was lost.',
    category: 'troubleshooting',
    audience: 'all',
    state: 'published',
    views: 119,
    helpfulPercent: 83,
    publishedDaysAgo: 128,
    keywords: ['onedrive', 'sync', 'paused', 'sharepoint', 'files', 'red cross'],
    service: 'microsoft-365',
    body: [
      p('OneDrive pauses syncing when your laptop is low on battery or disk space, on a metered connection, or after an update. Your files are safe on your laptop until it resumes.'),
      steps(
        ['Click the OneDrive cloud icon by the clock and choose ', bold('Resume syncing'), '.'],
        'If it pauses again straight away, check you have at least 5 GB free in File Explorer › This PC.',
        'Still stuck? Choose Settings › Account › Unlink this PC, then sign in again. OneDrive checks every file, which can take an hour for a large library.',
      ),
      p('Files with a red cross can’t sync — often because the name is too long or contains a character such as # or %. Rename them and they will catch up.'),
    ],
  },

  /* ---------------------------------------------- Policies (all staff) */
  {
    key: 'password-policy',
    title: 'Password rules',
    summary: 'How long, how often, and what we will never ask you for.',
    category: 'policies',
    audience: 'all',
    state: 'published',
    views: 81,
    helpfulPercent: 78,
    publishedDaysAgo: 233,
    keywords: ['password', 'policy', 'rules', 'expiry', 'passphrase'],
    service: 'identity-access',
    reused: true,
    body: [
      p('Your password protects everything you can reach at work. These rules apply to every account.'),
      bullets('At least 14 characters. A short sentence you can remember works well.', 'Changed only when you think it may be known to someone else — there is no routine expiry.', 'Never reused from another website or service.'),
      p('The service desk will never ask for your password, by phone, email or chat. If someone does, report it as an issue straight away.'),
    ],
  },
  {
    key: 'travel-devices',
    title: 'Taking company devices abroad',
    summary: 'Tell us before you travel outside the UK and EU with a laptop or phone.',
    category: 'policies',
    audience: 'all',
    state: 'published',
    views: 23,
    helpfulPercent: 86,
    publishedDaysAgo: 88,
    keywords: ['travel', 'abroad', 'laptop', 'roaming', 'overseas'],
    service: 'end-user-devices',
    reused: true,
    body: [
      p('Some countries restrict encrypted devices, and sign-ins from an unexpected country are blocked for your protection.'),
      bullets('Request “Travel with a device” at least five working days before you go.', 'Roaming is on for work phones in the EU; elsewhere we switch it on for the dates you travel.', 'Keep devices with you — never in checked luggage.'),
    ],
  },
  {
    key: 'acceptable-use',
    title: 'Acceptable use of IT',
    summary: 'The short version of the policy everyone agrees to.',
    category: 'policies',
    audience: 'all',
    state: 'published',
    views: 58,
    helpfulPercent: 80,
    publishedDaysAgo: 262,
    keywords: ['policy', 'acceptable use', 'personal use', 'software', 'lost device', 'usb'],
    body: [
      p('Company laptops and phones are for work. Reasonable personal use is fine; installing unlicensed software is not. Report a lost device straight away.'),
      bullets(
        ['Lock your screen with ', bold('Windows key + L'), ' whenever you leave your desk.'],
        'Keep work files in OneDrive, SharePoint or Teams — not on USB sticks or personal cloud storage.',
        'Don’t forward work email to a personal address.',
        'The software you need is in Company Portal; for anything else, use “Install software” in the service catalogue.',
      ),
      p('Lost a laptop or phone, or think someone has seen your password? Call the service desk on extension 4000 or email ', mail('security@northwind.example'), '. We can lock a device remotely within minutes.'),
      p('This is a summary. The full policy is in the Northwind Traders (UK) staff handbook, which everyone agrees to when they join.'),
    ],
  },

  /* ---------------------------------------------- Runbooks (IT only) */
  {
    key: 'rb-new-starter',
    title: 'New starter checklist',
    summary: 'What Identity & Security and End-User Computing do for a “New starter” request, in order.',
    category: 'runbooks',
    audience: 'internal',
    state: 'published',
    views: 61,
    helpfulPercent: 90,
    publishedDaysAgo: 210,
    keywords: ['new starter', 'joiner', 'onboarding', 'account', 'laptop', 'runbook'],
    service: 'identity-access',
    body: [
      p('Work the four tasks on the request in this order. HR raise the request at least five working days before the start date; if it arrives later, tell the hiring manager on the request what won’t be ready on day one.'),
      steps(
        'Create the account and mailbox in Entra ID from the HR record, with the start date as the account’s activation date.',
        'Assign licences and groups from the role template (Finance, Sales, Warehouse and so on), plus any extra access the manager asked for on the form.',
        'Prepare and image the laptop with the current build, and enrol it in Intune under the new starter’s name.',
        'Hand over the laptop and phone on the first morning, set up Microsoft Authenticator with them, and show them the Help Portal.',
      ),
      p('Leeds and Bristol starters: send the kit by tracked courier to the site’s facilities supervisor two working days before, not to the person.'),
    ],
  },
  {
    key: 'rb-leaver',
    title: 'Leaver checklist',
    summary: 'Disabling the account, forwarding mail and collecting kit when someone leaves.',
    category: 'runbooks',
    audience: 'internal',
    state: 'published',
    views: 44,
    helpfulPercent: 88,
    publishedDaysAgo: 210,
    keywords: ['leaver', 'offboarding', 'disable account', 'forward email', 'collect laptop', 'runbook'],
    service: 'identity-access',
    body: [
      p('The “Leaver” request gives the last day and who should receive the person’s email. Never disable an account before 17:30 on the last day unless HR ask in writing.'),
      steps(
        'Disable the account at the end of the last day and revoke its sign-in sessions in Entra ID.',
        'Forward email to the named colleague for 30 days, then convert the mailbox to a shared mailbox that colleague owns.',
        'Remove licences and group memberships, and move their OneDrive files to their line manager.',
        'Collect the laptop and phone. Record each asset as returned, or raise a lost-device ticket if it hasn’t come back within five working days.',
      ),
    ],
  },
  {
    key: 'rb-unlock-account',
    title: 'Unlock an account in Entra ID',
    summary: 'Check it’s really them, find out why it locked, then unlock.',
    category: 'runbooks',
    audience: 'internal',
    state: 'published',
    views: 132,
    helpfulPercent: 94,
    publishedDaysAgo: 190,
    keywords: ['unlock', 'locked out', 'account', 'entra id', 'password', 'runbook'],
    service: 'identity-access',
    body: [
      p('Accounts lock after ten wrong passwords in a row. A lockout the person didn’t cause can mean someone is guessing their password, so check before you unlock.'),
      steps(
        'Call the person back on the number in their HR record — never on a number they give you — and confirm their name and line manager.',
        'In the Entra admin centre, open the user’s sign-in logs and note where the failed attempts came from.',
        'If the failures came from an unfamiliar country or device, don’t unlock: pass the ticket to Identity & Security as a suspicious sign-in.',
        'Otherwise unlock the account, ask them to sign in once while you’re on the phone, and remind them that their phone may still be trying the old password.',
      ),
    ],
  },
  {
    key: 'rb-reset-mfa',
    title: 'Reset MFA for a user',
    summary: 'For a lost, replaced or wiped phone: verify, clear the old methods, and stay on the line while they set up again.',
    category: 'runbooks',
    audience: 'internal',
    state: 'published',
    views: 118,
    helpfulPercent: 91,
    publishedDaysAgo: 190,
    keywords: ['mfa', 'multi-factor', 'authenticator', 'reset', 'lost phone', 'runbook'],
    service: 'identity-access',
    body: [
      p('Resetting multi-factor sign-in lets anyone who knows the password register their own phone, so the identity check is the part that matters.'),
      steps(
        'Call the person on the desk or mobile number in their HR record and confirm two details from that record.',
        ['In the Entra admin centre, open the user, choose ', bold('Authentication methods'), ' and require them to register again.'],
        'Revoke their sessions, so sign-ins on the old phone stop working.',
        'Stay on the call while they set up Microsoft Authenticator on the new phone, then note on the ticket that the check was done.',
      ),
    ],
  },
  {
    key: 'rb-month-end',
    title: 'Sage Intacct month-end support rota',
    summary: 'Who covers Sage Intacct over the last three working days of the month, and what to check first.',
    category: 'runbooks',
    audience: 'internal',
    state: 'published',
    views: 39,
    helpfulPercent: 87,
    publishedDaysAgo: 140,
    keywords: ['month-end', 'sage intacct', 'rota', 'finance', 'bank file', 'payment run', 'runbook'],
    service: 'finance-systems',
    body: [
      p('Finance close the books over the last three working days of each month. Business Applications covers Sage Intacct from 07:30 to 19:00 on those days, and no changes to finance systems go in during the last two.'),
      bullets(
        'First call: Liam Walsh; second: Hannah Becker. The year’s rota is pinned in the Business Applications channel in Teams.',
        'Treat anything that stops the supplier payment run or the bank file as P2, whatever the caller says.',
        'If the bank rejects the payment file, check the supplier records added that week for badly formatted sort codes before anything else.',
        'Update the finance team on the ticket at least every hour, even when there is no news.',
      ),
    ],
  },
  {
    key: 'rb-major-incident',
    title: 'Major incident: the first 15 minutes',
    summary: 'Declare it, name the roles, open the bridge and send the first update.',
    category: 'runbooks',
    audience: 'internal',
    state: 'published',
    views: 52,
    helpfulPercent: 92,
    publishedDaysAgo: 120,
    keywords: ['major incident', 'declare', 'bridge', 'commander', 'stakeholder update', 'runbook'],
    body: [
      p('Declare a major incident when a service is down for a whole site or for more than 20 people, or when finance, the warehouse or customer service can’t work. If in doubt, declare it: standing it down costs nothing.'),
      steps(
        'Declare it in the Service Desk with a severity, the affected services and a one-line summary people outside IT will understand.',
        'Name a commander, a comms lead and a scribe. The on-call engineer commands until someone else takes over.',
        'Open the bridge in Teams and put the link on the incident.',
        'Send the first stakeholder update within 15 minutes, with the time of the next one — and keep that promise even when there is nothing new to say.',
        'Link every new report to the incident rather than working them one by one.',
      ),
      p('Customer-facing? The comms lead posts on the status page as well, and the IT Service Manager approves the wording.'),
    ],
  },

  /* ---------------------------------------------- Not published */
  {
    key: 'ricoh-printers',
    title: 'Using the new Ricoh printers',
    summary: 'Print, scan to email and collect your prints with your building pass.',
    category: 'how-to',
    audience: 'all',
    state: 'draft',
    views: 0,
    helpfulPercent: 0,
    publishedDaysAgo: 0,
    keywords: ['ricoh', 'printer', 'follow-me', 'pass', 'scan to email'],
    service: 'printing',
    body: [
      p('The new Ricoh printers hold your print job until you tap your building pass on the printer, so nothing sits in the tray for others to pick up.'),
      steps('Print as usual and choose “Northwind Follow-Me”.', 'At any Ricoh printer, tap your pass on the reader beside the screen.', 'Choose your job and press Print.'),
      p('To scan, tap Scan to Me: the scan arrives in your inbox as a PDF.'),
    ],
  },
  {
    key: 'expenses-sage',
    title: 'Submitting expenses in Sage Intacct',
    summary: 'Claim travel and other expenses, add receipts, and see where your claim is.',
    category: 'how-to',
    audience: 'all',
    state: 'in_review',
    views: 0,
    helpfulPercent: 0,
    publishedDaysAgo: 0,
    keywords: ['expenses', 'sage intacct', 'receipts', 'mileage', 'claim'],
    service: 'finance-systems',
    body: [
      p('Expenses are claimed in Sage Intacct and approved by your line manager. Claims submitted by the 20th are paid with that month’s salary.'),
      steps(['In Sage Intacct, choose ', bold('Time & Expenses'), ' › Expenses › Add.'], 'Add each item with its date, amount and expense type, and photograph the receipt.', 'Submit. Your manager gets an email asking them to approve it.'),
      p('Mileage is claimed at the current HMRC rate: enter the miles, not the amount.'),
    ],
  },
] satisfies readonly KnowledgeArticleContent[];
