import type { SlotBank, TitleLibrary } from '../plan/content-types.js';

/**
 * What people at Northwind type when they ask IT for help (A4 §1.13.1): at
 * least twelve titles and four descriptions for each of the 26 subcategories,
 * plus the "Called in: …" notes an agent types for a phoned-in ticket.
 *
 * The planner draws a title and a description independently, so every
 * description is written to read naturally under any title of its
 * subcategory — the title carries the specific fault, the description the
 * register (terse e-mail, friendly portal) and the circumstances. That is
 * also how real tickets read: "Outlook won’t open" over "Tried restarting,
 * no change. I’m at the Leeds DC today."
 *
 * Templates may use only the slots in `TICKET_SLOTS`; `{device}` and
 * `{colleague}` are filled by the planner (an asset tag, a colleague's first
 * name), the rest from `SLOTS` below. A slot's value is the same in a ticket's
 * title and its description, so "New starter: {colleague}" and "{colleague}’s
 * line manager here" name one person. Values are written to fit the sentences
 * they land in: every `since` reads after "It’s been like this", every `site`
 * after "I’m at", every `floor` after "on".
 */

export const SLOTS = {
  site: ['London HQ', 'the Leeds DC', 'the Bristol hub'],
  floor: ['the ground floor', 'the 1st floor', 'the 2nd floor', 'the 3rd floor', 'the 4th floor'],
  app: ['Salesforce', 'Sage Intacct', 'BambooHR', 'Power BI', 'SharePoint', 'the WMS', 'Teams', 'Outlook'],
  error: [
    'Something went wrong',
    'Access denied',
    'The operation timed out',
    'We couldn’t sign you in',
    'Unable to connect to the server',
    'An unexpected error has occurred',
    'Your session has expired',
  ],
  since: [
    'since this morning',
    'since Monday',
    'since yesterday afternoon',
    'since last night’s update',
    'since I got back from leave',
    'for the last couple of days',
    'on and off for a week',
  ],
  room: ['Thames', 'Severn', 'Aire', 'Avon'],
} satisfies SlotBank;

export const TITLES = {
  /* ---------------------------------------------- Access & identity */
  'password-sign-in': {
    titles: [
      'Locked out after changing my password',
      'Can’t sign in to {app} since my password change',
      'Account locked — can’t log in to my laptop',
      'Password expired message but I changed it last week',
      'Forgotten my password and the reset isn’t working',
      'Keep being asked to sign in to {app} again',
      'Locked out again this morning',
      'Laptop says my password is wrong but it works on my phone',
      'Can’t sign in on the goods-in PC',
      'Sign-in page just loops back to the start',
      'New password not accepted on the VPN',
      'Please reset my password — back from leave and can’t get in',
      'Password reset link says it has expired',
    ],
    descriptions: [
      'I can’t get in and it’s stopping me working. I’m at {site} on {floor}. It’s been like this {since}.',
      'Tried my password a few times and now I’m stuck. It says “{error}”. Could someone reset it or unlock me please?',
      'Hi, as the title says. I’m using laptop {device} and I’m around all day if you need to call.',
      'Please can someone help? {colleague} at the next desk tried the usual fix with me and it didn’t work.',
      'Not sure what’s happened — it was fine before. The message says “{error}”.',
    ],
    phoned: [
      'Called in: can’t sign in, as per the title. Caller is at {site}. Checked the account in Entra ID during the call.',
      'Phoned the desk: sign-in problem as per the title, happening {since}. Message on screen: “{error}”.',
    ],
  },
  mfa: {
    titles: [
      'Authenticator app not getting sign-in requests on my new phone',
      'MFA prompt I didn’t ask for',
      'New phone — need to move Microsoft Authenticator',
      'Lost my phone, can’t approve sign-ins',
      'Authenticator code not accepted',
      'Keep getting asked to approve sign-ins on my phone',
      'Need MFA reset — phone was wiped',
      'Can’t sign in to {app}: it says approve on my phone but nothing arrives',
      'Number in the Authenticator prompt doesn’t match the screen',
      'Authenticator app asking me to set up again',
      'Sign-in approvals going to my old phone',
      'Can’t get past the “Approve sign-in request” screen',
      'Locked out of MFA after changing my phone number',
    ],
    descriptions: [
      'I can’t get past the sign-in approval, so I can’t get into email or Teams on the laptop. It’s been like this {since}.',
      'Hi, as the title says. I’m at {site} today and can take a call on my desk phone to confirm it’s me.',
      'The message on the laptop says “{error}”. Happy to come down to the desk if that’s easier.',
      'Could someone sort this out please? Everything that asks me to approve a sign-in is stuck.',
      '{colleague} says the service desk can reset this for me. I’m on {floor} at {site}.',
    ],
    phoned: [
      'Called in: MFA problem as per the title. Verified the caller on the number in their HR record before doing anything.',
      'Phoned the desk: can’t complete the sign-in approval, happening {since}. Caller is at {site}.',
    ],
  },
  'mailbox-drive-access': {
    titles: [
      'Need access to the finance@ shared mailbox',
      'Access to the Sales Operations SharePoint site',
      'Please add me to the customerservice@ mailbox',
      'Can’t open the S: drive since this morning’s update',
      'Access to the Leeds operations shared drive',
      'Shared mailbox not showing in Outlook',
      'Need send-as rights on the orders@ mailbox',
      'Read access to the Marketing team site, please',
      'Access denied on the Finance folder',
      'Please give me access to the Bristol complaints mailbox',
      'Need edit rights on the pricing folder',
      'Add me to the HR shared calendar',
      'Access to the supplier contracts library',
    ],
    descriptions: [
      'Hi, I’ve moved roles and need this for my new work. My manager has said it’s fine. Thanks',
      'Could you set this up please? {colleague} already has it, if it helps to copy their access.',
      'Needed for my day-to-day work. I’m at {site} if you need me.',
      'As per the title, please. At the moment it says “{error}” when I try to open it.',
      'I’ve joined the team on {floor} and need the same access as everyone else here.',
    ],
    phoned: [
      'Called in: access needed as per the title. The caller’s manager has agreed; checked with them on Teams.',
      'Phoned the desk asking for the access in the title. Says it shows “{error}” when they try now.',
    ],
  },
  'joiners-leavers': {
    titles: [
      'New starter: {colleague} joins the warehouse team on Monday',
      'Leaver: {colleague} — last day Friday',
      'New starter in Finance next week — laptop and accounts for {colleague}',
      'Leaver: {colleague} (field sales) — collect laptop and phone',
      '{colleague} is moving from Bristol to London — access changes',
      'New starter: {colleague}, customer service, Bristol',
      'Leaver today — please disable {colleague}’s account at 17:30',
      'Temporary staff starting at the Leeds DC next week',
      'New starter: {colleague}, marketing — needs a laptop and phone',
      'Leaver: {colleague} — forward email to their manager',
      '{colleague} back from maternity leave — please re-enable account',
      'New starter: {colleague} (transport) — account and scanner login',
      'Leaver: {colleague} — remove access to Sage Intacct',
    ],
    descriptions: [
      'Everything you need should be in the form. HR have confirmed the dates; let me know if you need anything else from me.',
      'Raised on behalf of HR. Please make sure the IT side is ready for the date in the form.',
      'I’m {colleague}’s line manager. Please go ahead as per the form, and give me a shout if anything is unclear.',
      'Details as per the form. They’re based at {site}, so please send or collect kit there.',
      'Please see the title and form. Same access as the rest of the team unless the form says otherwise.',
    ],
    phoned: [
      'Called in by the line manager: details as per the title. Asked them to complete the form as well so HR have a record.',
      'Phoned the desk on behalf of HR: as per the title. Site: {site}.',
    ],
  },
  'app-access': {
    titles: [
      'Access to {app}, please',
      'Need {app} for my new role',
      'Access to the Salesforce reporting workspace',
      'Please add me to Power BI Pro',
      'Need read-only access to Sage Intacct',
      'Access to the WMS reports for the Leeds DC',
      'Can I have Tableau access?',
      'Need admin rights in BambooHR for holiday approvals',
      'Access to the customer portal admin pages',
      'Request access to {app} — started this week',
      'Need access to {app} before the training next week',
      'Zebra MDM console access for the shift supervisors',
      'Access to the Meraki dashboard for the Leeds site',
    ],
    descriptions: [
      'I need this for my day-to-day work. My manager has approved it. Thanks!',
      'Hi, could you set this up please? {colleague} has the same access if it helps to copy theirs.',
      'Just moved into the team at {site} and everyone else here has this. Read-only is fine to start with.',
      'As per the title. When I try now it says “{error}”.',
      'Needed for a project starting soon. Happy to answer any questions about it.',
    ],
    phoned: [
      'Called in: access request as per the title. Told them their manager will be asked to approve it.',
      'Phoned the desk: needs the access in the title. Currently sees “{error}”.',
    ],
  },

  /* ---------------------------------------------- Software & Microsoft 365 */
  outlook: {
    titles: [
      'Outlook keeps asking for my password',
      'Emails stuck in my outbox',
      'Outlook won’t open — stuck on “Loading profile”',
      'Calendar invites not showing in Outlook',
      'Outlook search doesn’t find older emails',
      'Can’t see my colleague’s calendar any more',
      'Outlook very slow since the update',
      'Emails from a supplier going to junk',
      'My email signature has disappeared',
      'Meeting room not showing in the Outlook room finder',
      'Outlook says my mailbox is almost full',
      'Attachments won’t open in Outlook',
      'Outlook crashes when I reply to an email',
    ],
    descriptions: [
      'It’s Outlook on my laptop ({device}). Webmail seems fine, so I think it’s just the app. It’s been like this {since}.',
      'Tried closing Outlook and restarting the laptop, no change. I’m at {site} today if someone can take a look.',
      'Not urgent, but it’s slowing me down. {colleague} next to me doesn’t have the problem.',
      'As per the subject. Error says “{error}” if that helps.',
      'Hi, please could someone look at this? It’s been happening {since} and I live in Outlook all day.',
    ],
    phoned: [
      'Called in: Outlook problem as per the title, happening {since}. Checked webmail with the caller and it works.',
      'Phoned the desk: Outlook issue on laptop {device}. Caller restarted once, no change.',
    ],
  },
  teams: {
    titles: [
      'Teams calls drop after a few minutes on Wi-Fi',
      'Teams camera not detected after update',
      'People can’t hear me on Teams calls',
      'Teams keeps signing me out',
      'Can’t share my screen in Teams meetings',
      'Teams messages arrive hours late',
      'Teams won’t open — just a white screen',
      'Can’t join external Teams meetings',
      'Missing from a team channel I was added to',
      'Teams notifications stopped working',
      'Echo on Teams calls from the {room} room',
      'Teams status stuck on “Away”',
      'Teams very slow and the laptop fan goes mad',
    ],
    descriptions: [
      'It’s been like this {since}. I’ve restarted Teams and the laptop and it’s still the same.',
      'Happens most days now, and it’s embarrassing on customer calls. I’m at {site}.',
      'Laptop is {device}. Teams on my phone works fine, so it seems to be the laptop.',
      'As per the subject. {colleague} has the same thing, so it may not just be me.',
      'Error says “{error}”. Could someone take a look please?',
    ],
    phoned: [
      'Called in: Teams problem as per the title, happening {since}. Teams on the caller’s phone works.',
      'Phoned the desk: Teams issue on {device}. Caller is at {site}; restarted Teams with them, no change.',
    ],
  },
  'office-apps': {
    titles: [
      'Excel crashes when I open a large workbook',
      'Word document won’t save to SharePoint',
      'PowerPoint freezes when I add a video',
      'Excel formulas showing as text',
      'Office says it isn’t activated',
      'Can’t open a file from a customer — Protected View error',
      'Track changes not showing in Word',
      'Excel very slow with the pricing model',
      'Macros blocked in a spreadsheet from Finance',
      'How do I recover an unsaved Word document?',
      'PowerPoint template missing the new logo',
      'Excel keeps asking which version to keep',
      'Copy and paste stopped working in Excel',
    ],
    descriptions: [
      'Happens with this one file but others are fine. Laptop is {device}.',
      'It’s been doing this {since}. I’ve restarted and it hasn’t helped.',
      'I need this for a deadline today, so anything you can do quickly would be great. I’m at {site}.',
      'Message says “{error}”. {colleague} doesn’t have the same problem on their laptop.',
      'Not sure if it’s me or the file. Could someone have a look?',
    ],
    phoned: [
      'Called in: Office problem as per the title. Laptop {device}; caller has restarted once.',
      'Phoned the desk: issue as per the title, happening {since}. Message on screen: “{error}”.',
    ],
  },
  'install-request': {
    titles: [
      'Please install Power BI Desktop',
      'Install Adobe Acrobat Pro',
      'Need Visio for process maps',
      'Can I have Notepad++ installed?',
      'Install the Zebra label printing software',
      'Need Microsoft Project for the warehouse move',
      'Please install Tableau Desktop',
      'Install 7-Zip please',
      'Need the Sage Intacct Excel add-in',
      'Snagit for writing training guides',
      'Install Python for the pricing analysis',
      'Need Zoom for a customer who won’t use Teams',
      'Please install the Salesforce add-in for Outlook',
    ],
    descriptions: [
      'I need this for my work and it isn’t in Company Portal. The free version is fine if there is one.',
      'Could this be installed on my laptop ({device}) please? My manager is happy for me to have it.',
      'Needed for a project with {colleague}’s team. Thanks in advance.',
      'As per the title. I couldn’t find it in Company Portal.',
      'Hi, please could you install this? I’m at {site} and around all day.',
    ],
    phoned: [
      'Called in: software install as per the title. Checked Company Portal with the caller; it isn’t there.',
      'Phoned the desk asking for the software in the title on laptop {device}.',
    ],
  },
  'onedrive-sharepoint': {
    titles: [
      'OneDrive says “Sync paused” and won’t restart',
      'Files missing from SharePoint after I saved them',
      'Can’t open a SharePoint file in the desktop app',
      'OneDrive full — how do I free up space?',
      'Shared link to a customer doesn’t work',
      'Two copies of the same file in OneDrive',
      'SharePoint site very slow',
      'Can’t see a folder {colleague} shared with me',
      'Red crosses on lots of files in OneDrive',
      'Restore a deleted folder from SharePoint',
      'File locked for editing by someone who’s left',
      'Teams files not syncing to File Explorer',
      'Excel file opens read-only from SharePoint',
    ],
    descriptions: [
      'It’s been like this {since}. I’ve signed out of OneDrive and back in, no change.',
      'Laptop is {device}. Other files seem fine, it’s just this one area.',
      'I need these files for work today, so I’d be grateful for a quick look. I’m at {site}.',
      'Error says “{error}”. {colleague} can see the same folder and it works for them.',
      'Hi, as per the title. Not sure whether it’s OneDrive or SharePoint, sorry.',
    ],
    phoned: [
      'Called in: OneDrive or SharePoint problem as per the title, happening {since}.',
      'Phoned the desk: as per the title. Message on screen: “{error}”. Laptop {device}.',
    ],
  },

  /* ---------------------------------------------- Hardware */
  laptop: {
    titles: [
      'Laptop fan very loud and battery lasts about an hour',
      'Laptop won’t turn on',
      'Laptop very slow since the update',
      'Cracked laptop screen',
      'Some keyboard keys not working',
      'Need a replacement laptop — mine is four years old',
      'Laptop overheating when docked',
      'Laptop won’t charge',
      'Blue screen errors several times a day',
      'Request a performance laptop for Power BI',
      'Laptop touchpad jumping around',
      'Spilt coffee on my laptop',
      'Loan laptop needed while mine is repaired',
    ],
    descriptions: [
      'Laptop is {device}. I’m at {site} on {floor} if someone needs to look at it.',
      'It’s been like this {since}. I can still work, but only just.',
      'Could someone help please? I’m out at a customer tomorrow and need a laptop I can rely on.',
      'Hi, as per the title. {colleague} said to raise it here. Asset tag is {device}.',
      'Not sure if this needs a new laptop or a repair. I’m in the office all week.',
    ],
    phoned: [
      'Called in: laptop {device}, as per the title. Caller is at {site}; asked them to bring it to the desk if they can.',
      'Phoned the desk: laptop problem as per the title, happening {since}.',
    ],
  },
  'monitor-dock': {
    titles: [
      'Second monitor flickers on the dock',
      'Laptop won’t wake from sleep when docked',
      'Need a second monitor',
      'Dock not charging my laptop',
      'Monitor says “No signal”',
      'Need a dock for my new desk',
      'Screens go black for a few seconds every so often',
      'Wrong resolution on my external monitor',
      'USB keyboard and mouse stop working on the dock',
      'Monitor and dock for home working',
      'Monitor arm broken',
      'Headset and webcam for working from home',
      'Wired network not working through the dock',
    ],
    descriptions: [
      'I’m on {floor} at {site}, by the window. Laptop is {device}.',
      'Could someone help with this please? It’s been like this {since}.',
      'Hi, as per the title. {colleague} has the same set-up and theirs is fine.',
      'Not urgent, but it would make a big difference. Thanks!',
      'Asset tag on the laptop is {device} if you need it. I’m in most days this week.',
    ],
    phoned: [
      'Called in: monitor or dock, as per the title. Caller is on {floor} at {site}.',
      'Phoned the desk: as per the title. Laptop {device}.',
    ],
  },
  printer: {
    titles: [
      'Can’t print to PRN-LDS-02 (Leeds goods-in)',
      'Printer shows as offline',
      'Paper jam message but there’s no paper stuck',
      'Printing comes out blank',
      'Print jobs stuck in the queue',
      'Printer on {floor} not scanning to email',
      'Colour printing very faint',
      'Delivery notes printing across two labels',
      'Can’t find the new printer on my laptop',
      'Printer asking for a PIN I don’t have',
      'Toner low on the printer on {floor}',
      'Printer on {floor} printing very slowly',
      'Double-sided printing not working',
      'Label printer in the warehouse not printing',
    ],
    descriptions: [
      'It’s happening for everyone on our side of {floor}. Others can print fine.',
      'I’m at {site}. It’s been like this {since}.',
      'Tried turning the printer off and on, no change. {colleague} has the same problem.',
      'Message on the printer’s screen says “{error}”.',
      'Not urgent, but we need it for this afternoon’s post. Thanks.',
    ],
    phoned: [
      'Called in: printer problem as per the title, at {site}. Caller has turned it off and on.',
      'Phoned the desk: as per the title. Happening {since}.',
    ],
  },
  mobile: {
    titles: [
      'Cracked screen on my work iPhone',
      'Work phone won’t charge',
      'Need a work mobile for my new role',
      'Email stopped syncing on my phone',
      'Phone battery drains by lunchtime',
      'Upgrade request — phone is very old and slow',
      'No Teams notifications on my phone',
      'Mobile data not working abroad',
      'Need my SIM moved to a new phone',
      'Phone stuck on the Apple logo',
      'Work phones for the warehouse supervisors',
      'Voicemail not working on my work phone',
      'Company Portal says my phone isn’t compliant',
    ],
    descriptions: [
      'I rely on it when I’m away from my desk, so the sooner the better.',
      'Hi, as per the title. I’m at {site} if someone needs to see it.',
      'Could someone help please? {colleague} said to raise it here.',
      'Not urgent, but I need it sorted this week if possible.',
      'I’m out and about a lot, so email is the best way to reach me. Thanks!',
    ],
    phoned: [
      'Called in: mobile phone, as per the title. Caller is at {site}.',
      'Phoned the desk: work phone, as per the title. Caller prefers email updates.',
    ],
  },

  /* ---------------------------------------------- Business applications */
  salesforce: {
    titles: [
      'Salesforce report “Pipeline by region” shows no data',
      'Need a Salesforce licence for our new account manager',
      'Can’t log a call against an account in Salesforce',
      'Salesforce very slow this morning',
      'Opportunity stuck at the approval stage',
      'Add a new product to the Salesforce price book',
      'Duplicate accounts after the import',
      'Salesforce dashboard not refreshing',
      'Can’t see my team’s opportunities',
      'Salesforce add-in not logging my emails',
      'Change the owner of 40 accounts',
      'Quote PDF missing the new logo',
      'Salesforce mobile app won’t sync',
    ],
    descriptions: [
      'This is holding up the sales team. It’s been like this {since}.',
      'Hi, as per the title. {colleague} sees the same thing.',
      'Could someone in the Salesforce team take a look please? I’m at {site} today.',
      'We need this before the Monday sales call if possible. Thanks!',
      'Not urgent, but it would help a lot. Happy to explain more on a call.',
    ],
    phoned: [
      'Called in: Salesforce, as per the title. Caller is at {site}.',
      'Phoned the desk about Salesforce, as per the title. Caller is happy to be contacted on Teams.',
    ],
  },
  'sage-intacct': {
    titles: [
      'Sage Intacct bank file rejected — supplier payment run',
      'Can’t post journals in Sage Intacct',
      'Sage Intacct report times out',
      'Supplier invoice stuck in approval',
      'Need access to the Leeds entity in Sage Intacct',
      'Period won’t lock for the month-end close',
      'Sage Intacct Excel add-in not connecting',
      'VAT report figures look wrong',
      'Purchase order won’t convert to an invoice',
      'Sage Intacct says my session has expired every few minutes',
      'Bank feed hasn’t updated since yesterday',
      'Expense claims not showing for approval',
      'Credit note won’t apply to an invoice',
    ],
    descriptions: [
      'This is holding up the finance team. It’s been like this {since}.',
      'Hi, as per the title. {colleague} has tried it too and gets the same.',
      'We need this sorted today if at all possible. I’m at {site}.',
      'Could someone in Business Applications have a look please?',
      'Message in Sage Intacct says “{error}”.',
    ],
    phoned: [
      'Called in from Finance: Sage Intacct, as per the title. Happening {since}.',
      'Phoned the desk: Sage Intacct issue as per the title. Message: “{error}”.',
    ],
  },
  bamboohr: {
    titles: [
      'BambooHR won’t let me approve holiday for my team',
      'Can’t sign in to BambooHR — sign-in loop',
      'Holiday balance wrong in BambooHR',
      'Need manager access in BambooHR',
      'New starter not showing in BambooHR',
      'Payslip not showing in BambooHR',
      'BambooHR app won’t open on my phone',
      'Wrong manager shown in BambooHR',
      'Sickness record not saving in BambooHR',
      'BambooHR emails going to junk',
      'Org chart in BambooHR out of date',
      'How do I book a half day in BambooHR?',
      'Team calendar in BambooHR is blank',
    ],
    descriptions: [
      'It’s been like this {since}. I’ve tried another browser too.',
      'Hi, as per the title. {colleague} in HR says it isn’t just me.',
      'Could someone take a look please? I’m at {site}.',
      'Not urgent, but people are waiting on me. Thanks!',
      'When I try, it says “{error}”.',
    ],
    phoned: [
      'Called in: BambooHR, as per the title. Caller is at {site}.',
      'Phoned the desk about BambooHR: as per the title, happening {since}.',
    ],
  },
  wms: {
    titles: [
      'WMS scanner on dock 4 won’t log in',
      'WMS very slow on the warehouse floor',
      'Pick lists not printing from the WMS',
      'Stock levels in the WMS don’t match the shelf',
      'Can’t close a delivery in the WMS',
      'WMS showing the wrong bay for a product',
      'New picker needs a WMS login',
      'WMS error when booking in a delivery',
      'Orders not dropping into the WMS from Salesforce',
      'Scanner says “User not authorised”',
      'WMS freezes at shift change',
      'Replenishment tasks not appearing',
      'Goods-in screen won’t accept the delivery note number',
    ],
    descriptions: [
      'This is holding up picking at {site}. It’s been like this {since}.',
      'Happening on several scanners, not just one. {colleague} on the late shift saw it too.',
      'Message on the screen says “{error}”.',
      'We’ve got a lorry waiting, so anything quick would be great.',
      'Hi, as per the title. The shift supervisor is around if you need more detail.',
    ],
    phoned: [
      'Called in from the warehouse: WMS, as per the title. Message: “{error}”.',
      'Phoned the desk from {site}: as per the title, happening {since}.',
    ],
  },

  /* ---------------------------------------------- Network */
  vpn: {
    titles: [
      'VPN disconnects every 20 minutes when working from home',
      'VPN says “Authentication failed”',
      'Can’t connect to the VPN from a hotel',
      'VPN very slow from home',
      'Need VPN access for working from home',
      'VPN client missing after the update',
      'VPN connects but I can’t reach the S: drive',
      'VPN certificate expired message',
      'VPN access for a contractor',
      'VPN won’t connect on my home Wi-Fi',
      'VPN drops when I join a Teams call',
      'Can’t reach Sage Intacct over the VPN',
      'VPN stuck on “Connecting…”',
    ],
    descriptions: [
      'I work from home two days a week, so I need this sorted before then. Laptop is {device}.',
      'Hi, as per the title. I’m back in the office at {site} later in the week if that’s easier.',
      'Could someone help please? It’s been like this {since}.',
      'Error says “{error}”.',
      'Not sure if this is a VPN thing or a laptop thing, so raising it here.',
    ],
    phoned: [
      'Called in from home: VPN, as per the title. Laptop {device}.',
      'Phoned the desk: VPN problem as per the title, happening {since}.',
    ],
  },
  wifi: {
    titles: [
      'No Wi-Fi in the Bristol training room',
      'Leeds DC: handheld scanners dropping off the network in aisle 12',
      'Wi-Fi very slow on {floor}',
      'Guest Wi-Fi for a visitor tomorrow',
      'Laptop keeps dropping off Northwind-Corp',
      'Can’t connect my phone to Northwind-Staff',
      'Wi-Fi drops in the {room} room',
      'No Wi-Fi signal by the loading bay',
      'Wi-Fi asks for a password every morning',
      'Guest Wi-Fi codes not working at reception',
      'Wi-Fi fine at my desk but not in meeting rooms',
      'Scanners losing connection near the chiller',
      'Wi-Fi slow during video calls',
    ],
    descriptions: [
      'It’s been like this {since}. Wired connections seem fine.',
      'Hi, as per the title. I’m at {site} on {floor}.',
      '{colleague} has the same problem, so it isn’t just my laptop.',
      'Could someone take a look please? It’s affecting a few of us.',
      'Message on the laptop says “{error}”.',
    ],
    phoned: [
      'Called in: Wi-Fi, as per the title. Caller is at {site}; wired works.',
      'Phoned the desk: Wi-Fi problem as per the title, happening {since}.',
    ],
  },
  'site-connectivity': {
    titles: [
      'Leeds DC: no internet on the warehouse PCs',
      'Bristol hub phones and internet down',
      'Very slow connection to London systems from Leeds',
      'Site link down at the Bristol hub',
      'Internet dropping out every few minutes at {site}',
      'Can’t reach the WMS from the Leeds offices',
      'Network down in the goods-in office',
      'Whole floor lost network on {floor}',
      'Phones in Bristol customer service dropping calls',
      'Everything very slow at {site} this morning',
      'No network in the Leeds transport office',
      'Shared drives unreachable from Bristol',
      'Card terminal at reception offline',
    ],
    descriptions: [
      'Several of us are affected, not just me. It’s been like this {since}.',
      'This is stopping work at {site}. Please treat it as urgent.',
      'Hi, as per the title. {colleague} checked the cables in the comms cupboard and the lights are on.',
      'Message on screen says “{error}”.',
      'Calls are dropping and systems are crawling. Can someone look urgently?',
    ],
    phoned: [
      'Called in from {site}: site connectivity, as per the title. Several users affected.',
      'Phoned the desk: as per the title, happening {since}. Passed to Network straight away.',
    ],
  },

  /* ---------------------------------------------- Security */
  phishing: {
    titles: [
      'Suspicious email claiming to be from DHL about a customs charge',
      'Phishing email pretending to be from Microsoft',
      'Email asking me to update bank details for a supplier',
      'Fake invoice from a supplier we use',
      'Email from “the MD” asking for gift cards',
      'Suspicious Teams message from an outside account',
      'Odd email with a QR code to “re-verify” my account',
      'Voicemail email with a strange attachment',
      'Is this email from HMRC genuine?',
      'Parcel delivery text on my work phone',
      'Suspicious DocuSign request',
      'Email asking me to share a password',
      'Email with a link to a “shared document” from someone I don’t know',
    ],
    descriptions: [
      'I didn’t click anything. I’ve forwarded it as an attachment as the training says.',
      'Not sure if this is genuine, so checking before I do anything with it.',
      'A few of us at {site} have had the same one. {colleague} nearly replied to it.',
      'Reporting this as asked in the security training. I haven’t opened the attachment or link.',
      'It looks very convincing. Can someone check it please?',
    ],
    phoned: [
      'Called in: suspicious message as per the title. Caller didn’t click; asked them to forward it as an attachment.',
      'Phoned the desk to report the message in the title. Others at {site} have had it too.',
    ],
  },
  'suspicious-sign-in': {
    titles: [
      'MFA prompt I didn’t ask for at 02:14',
      'Email saying someone signed in from another country',
      'Sign-in alert from an unfamiliar location',
      'Repeated approval requests I didn’t make',
      'Account locked and I didn’t try to sign in',
      'Emails in my Sent folder I didn’t send',
      'Someone changed my out-of-office',
      'New inbox rule I didn’t create',
      'Password reset email I didn’t ask for',
      'Strange sign-in on my account at the weekend',
      'Alert: impossible travel sign-in',
      'Colleague received an odd email from my address',
      'Phone keeps asking me to approve sign-ins overnight',
    ],
    descriptions: [
      'I didn’t approve anything. Should I change my password?',
      'I haven’t travelled anywhere and I don’t recognise this at all. Worried someone has my password.',
      'Reporting this straight away as the training says. I’m at {site} today.',
      'I don’t recognise this. {colleague} suggested I raise it here.',
      'Not sure if it’s serious but it doesn’t look right. Please could someone check?',
    ],
    phoned: [
      'Called in: possible account compromise as per the title. Verified the caller and passed straight to Identity & Security.',
      'Phoned the desk worried about the alert in the title. Caller has not approved any request.',
    ],
  },
  'lost-stolen-device': {
    titles: [
      'Left my laptop on the train (Leeds to King’s Cross)',
      'Work phone stolen',
      'Lost my laptop bag at a customer’s',
      'Laptop stolen from my car',
      'Can’t find my work phone — think I left it in a taxi',
      'Lost my building pass and phone',
      'Tablet missing from the warehouse office',
      'Phone lost on holiday',
      'Laptop left in a hotel',
      'Bag stolen with laptop {device} in it',
      'Lost a USB stick with work files on it',
      'Phone lost at a trade show',
      'Laptop missing after the office move',
    ],
    descriptions: [
      'I’ve reported it to lost property. Please lock it so nobody can get into it.',
      'I think the asset tag is {device}. I’ve checked everywhere I’ve been today.',
      'Really sorry. What do I need to do? I’m at {site} tomorrow.',
      'It had my email and Teams on it. It is locked with a passcode.',
      'Reporting it straight away as the policy says. {colleague} has my desk number if you need to call.',
    ],
    phoned: [
      'Called in: lost or stolen device as per the title. Locked it remotely in Intune during the call.',
      'Phoned the desk to report the device in the title. Advised the caller to report it to the police if it was stolen.',
    ],
  },

  /* ---------------------------------------------- Facilities & how-to */
  'meeting-room-av': {
    titles: [
      'Screen in the {room} room won’t show my laptop',
      'No sound from the {room} room speakers',
      'Teams Rooms console frozen in {room}',
      'Camera in the {room} room pointing at the wall',
      'Board meeting in {room} — screen not working',
      'Wireless sharing not working in the meeting rooms',
      'Microphone in {room} picks up nothing',
      'Booking panel outside {room} is blank',
      'Echo on calls from the {room} room',
      'USB-C cable missing in {room}',
      'Can’t join a Zoom meeting from the {room} console',
      'Training room projector very dim',
      'Presentation clicker not working',
    ],
    descriptions: [
      'The meeting starts soon and we have customers in. Could someone come up please?',
      'Tried unplugging and plugging back in, no change. It says “{error}”.',
      'It’s been like this {since}. {colleague} had the same problem in an earlier meeting.',
      'Not urgent today, but we have an all-hands in there later in the week.',
      'Hi, as per the title. We’ve used the room next door for now.',
    ],
    phoned: [
      'Called in from the meeting room: as per the title. Sent someone up.',
      'Phoned the desk: meeting-room problem as per the title, happening {since}.',
    ],
  },
  questions: {
    titles: [
      'How do I set an out-of-office on my phone?',
      'How do I book a hot desk on the 3rd floor?',
      'Where do I find the expenses form?',
      'How do I add a shared calendar?',
      'Can I use my own laptop for work?',
      'How do I change my profile photo in Teams?',
      'Where are the printer drivers for a Mac?',
      'How do I recover a deleted email?',
      'What’s the Wi-Fi for visitors?',
      'How do I set up my email signature?',
      'Who do I ask about a new desk phone?',
      'How do I share a large file with a customer?',
      'Is there a guide to Teams for new starters?',
    ],
    descriptions: [
      'Sorry if this is a silly question! I couldn’t find it on the portal.',
      'First week here and nobody’s quite sure. I’m at {site}.',
      'Quick question, no rush. Thanks!',
      '{colleague} said the service desk would know. Thanks in advance.',
      'I had a look in the knowledge base but couldn’t see it.',
    ],
    phoned: [
      'Called in with a how-to question, as per the title. Sent them the relevant article.',
      'Phoned the desk: question as per the title. Caller is at {site}.',
    ],
  },
} satisfies TitleLibrary;
