import type { ShotAsset, ShotId } from '../shots.config.js';

/**
 * The captured landing pictures, by shot id (SPEC v3 §6.2; A5 §5.2–§5.4).
 *
 * GENERATED by `pnpm site:shots` (`infra/scripts/capture-site-shots.ts`, the
 * final wave): static imports of the encoded files, so Next hashes them under
 * `/_next/static/media/` with an immutable cache. Do not edit by hand.
 *
 * Empty until then. A shot with no entry is drawn by `Shot` as a small
 * server-rendered picture of that screen labelled "Sample data", never as a
 * "coming soon" box (X-M9); `site-release.test.ts` refuses a release while
 * any shot in `shots.config.ts` is missing here.
 */
export const SHOT_MANIFEST: Readonly<Partial<Record<ShotId, ShotAsset>>> = Object.freeze({});
